### ISSUE TITLE
Demasiadas dependencia de terceros 

### ISSUE THREAD

**Issue by JeanRoldanDev** [paymentez/paymentez-flutter#2]
Comprendo no reinventar la rueda y usar dio y crypto, pero no debería ser mas propio?
Aun no tenemos respuesta de si tendremos un modulo o plugin oficial para flutter  :(

![image](https://user-images.githubusercontent.com/6289980/92499072-0dc1ac80-f1c1-11ea-8155-9f71ac0f7176.png)

**Comment by Xndy** [comment]
como haras la integracion de paymentez con flutter ?

**Comment by aspoveda95** [comment]
Con lo que hay se puede agregar la tarjeta de un cliente por medio del channel de Paymentez por android. La cosa es que no hay con iOS.

**Comment by Xndy** [comment]
si ... mi idea pienso yo rs trabajar con el metodo de Debit Card Frame y mostrarlo en un webview y dejar esperando la transaccion y responder mediante un WebSocket solo que aqui no se si se perderá la conexion =/ =(

**Comment by JeanRoldanDev** [comment]
https://github.com/JeanRoldanDev/paymentezSDK
